/**
 * CandidatesPanel Component
 *
 * Displays trade candidates generated by the automated scanner.
 * Shows scored and ranked candidates with their triggers, technical
 * analysis, and recommended strategies. Allows users to view details,
 * dismiss candidates, or create proposals.
 */

import React, { useState, useCallback } from 'react';

// ============================================================================
// Types
// ============================================================================

/**
 * Trigger data for a candidate
 */
export interface CandidateTriggerData {
  type: string;
  description: string;
  value?: number | string;
  threshold?: number | string;
  strength: 'weak' | 'moderate' | 'strong';
}

/**
 * Research reference for a candidate
 */
export interface ResearchReferenceData {
  id: string;
  headline: string;
  sentiment?: 'bullish' | 'bearish' | 'neutral' | 'mixed';
  sourceName: string;
  publishedAt: string;
  trustScore: number;
}

/**
 * Score breakdown for a candidate
 */
export interface ScoreBreakdownData {
  technicalScore: number;
  researchScore: number;
  liquidityScore: number;
  ivRankScore?: number;
}

/**
 * Technical analysis data for a candidate
 */
export interface TechnicalAnalysisData {
  symbol: string;
  currentPrice: number;
  rsi?: {
    value: number;
    interpretation: string;
  };
  trend: {
    direction: 'bullish' | 'bearish' | 'neutral';
    signals: string[];
  };
  atr?: {
    value: number;
    valuePercent: number;
    interpretation: string;
  };
}

/**
 * Trade candidate data for UI display
 */
export interface TradeCandidateData {
  id: string;
  symbol: string;
  currentPrice: number;
  generatedAt: Date;
  triggers: CandidateTriggerData[];
  technicals: TechnicalAnalysisData;
  researchContext: ResearchReferenceData[];
  score: number;
  scoreBreakdown: ScoreBreakdownData;
  suggestedStrategy: string;
  strategyRationale: string;
  proposalId?: string;
  status: 'new' | 'viewed' | 'dismissed' | 'actioned';
  warnings: string[];
}

/**
 * Scanner configuration for display
 */
export interface ScannerConfigData {
  symbolsToScan: string[];
  pollingEnabled: boolean;
  pollingIntervalMs: number;
  minScore: number;
  generateProposals: boolean;
}

/**
 * Scanner statistics
 */
export interface ScannerStatsData {
  totalCandidates: number;
  byStatus: Record<string, number>;
  byStrategy: Record<string, number>;
  averageScore: number;
  lastScanAt?: Date;
}

export interface CandidatesPanelProps {
  /** Candidates to display */
  candidates: TradeCandidateData[];
  /** Scanner configuration */
  config: ScannerConfigData;
  /** Scanner statistics */
  stats: ScannerStatsData;
  /** Whether scanner is currently running */
  isScanning?: boolean;
  /** Whether polling is active */
  isPolling?: boolean;
  /** Callback to run a manual scan */
  onScan?: () => void;
  /** Callback to start/stop polling */
  onTogglePolling?: () => void;
  /** Callback when candidate is viewed */
  onViewCandidate?: (candidateId: string) => void;
  /** Callback when candidate is dismissed */
  onDismissCandidate?: (candidateId: string, reason?: string) => void;
  /** Callback when proposal is requested */
  onCreateProposal?: (candidateId: string) => void;
  /** Callback when approval modal should open */
  onApproveCandidate?: (candidateId: string) => void;
  /** Callback to update configuration */
  onUpdateConfig?: (updates: Partial<ScannerConfigData>) => void;
}

// ============================================================================
// Helper Functions
// ============================================================================

function formatTimestamp(date: Date): string {
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);

  if (diffMins < 1) return 'Just now';
  if (diffMins === 1) return '1 minute ago';
  if (diffMins < 60) return `${diffMins} minutes ago`;

  const diffHours = Math.floor(diffMins / 60);
  if (diffHours === 1) return '1 hour ago';
  if (diffHours < 24) return `${diffHours} hours ago`;

  return date.toLocaleDateString();
}

function formatStrategy(strategy: string): string {
  const names: Record<string, string> = {
    long_call: 'Long Call',
    long_put: 'Long Put',
    short_call: 'Short Call',
    short_put: 'Short Put',
    covered_call: 'Covered Call',
    cash_secured_put: 'Cash-Secured Put',
    vertical_spread: 'Vertical Spread',
    calendar_spread: 'Calendar Spread',
    iron_condor: 'Iron Condor',
    straddle: 'Straddle',
    strangle: 'Strangle',
    custom: 'Custom',
  };
  return names[strategy] || strategy;
}

function formatTriggerType(type: string): string {
  const names: Record<string, string> = {
    rsi_oversold: 'RSI Oversold',
    rsi_overbought: 'RSI Overbought',
    golden_cross: 'Golden Cross',
    death_cross: 'Death Cross',
    price_above_ma: 'Price Above MA',
    price_below_ma: 'Price Below MA',
    high_volatility: 'High Volatility',
    low_volatility: 'Low Volatility',
    bullish_news: 'Bullish News',
    bearish_news: 'Bearish News',
    earnings_upcoming: 'Earnings Upcoming',
    catalyst_present: 'Catalyst Present',
  };
  return names[type] || type;
}

function getScoreColor(score: number): string {
  if (score >= 75) return 'score-high';
  if (score >= 50) return 'score-medium';
  return 'score-low';
}

function getStrengthBadge(strength: CandidateTriggerData['strength']): string {
  switch (strength) {
    case 'strong': return 'badge-strong';
    case 'moderate': return 'badge-moderate';
    case 'weak': return 'badge-weak';
    default: return '';
  }
}

function getTrendIcon(direction: 'bullish' | 'bearish' | 'neutral'): string {
  switch (direction) {
    case 'bullish': return '/\\';
    case 'bearish': return '\\/';
    case 'neutral': return '--';
    default: return '?';
  }
}

function getSentimentBadge(sentiment?: string): string {
  switch (sentiment) {
    case 'bullish': return 'sentiment-bullish';
    case 'bearish': return 'sentiment-bearish';
    case 'neutral': return 'sentiment-neutral';
    case 'mixed': return 'sentiment-mixed';
    default: return '';
  }
}

function formatPrice(price: number): string {
  return `$${price.toFixed(2)}`;
}

// ============================================================================
// Component Implementation
// ============================================================================

export const CandidatesPanel: React.FC<CandidatesPanelProps> = ({
  candidates,
  config,
  stats,
  isScanning = false,
  isPolling = false,
  onScan,
  onTogglePolling,
  onViewCandidate,
  onDismissCandidate,
  onCreateProposal,
  onApproveCandidate,
  onUpdateConfig,
}) => {
  const [expandedCandidateId, setExpandedCandidateId] = useState<string | null>(null);
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [sortBy, setSortBy] = useState<'score' | 'time' | 'symbol'>('score');
  const [dismissReason, setDismissReason] = useState('');
  const [showDismissDialog, setShowDismissDialog] = useState<string | null>(null);

  // Filter and sort candidates
  const filteredCandidates = candidates.filter((c) => {
    if (filterStatus === 'all') return true;
    return c.status === filterStatus;
  });

  const sortedCandidates = [...filteredCandidates].sort((a, b) => {
    switch (sortBy) {
      case 'score':
        return b.score - a.score;
      case 'time':
        return b.generatedAt.getTime() - a.generatedAt.getTime();
      case 'symbol':
        return a.symbol.localeCompare(b.symbol);
      default:
        return 0;
    }
  });

  const handleToggleExpand = useCallback((candidateId: string) => {
    setExpandedCandidateId((prev) => (prev === candidateId ? null : candidateId));
    if (onViewCandidate) {
      onViewCandidate(candidateId);
    }
  }, [onViewCandidate]);

  const handleDismiss = useCallback((candidateId: string) => {
    if (onDismissCandidate) {
      onDismissCandidate(candidateId, dismissReason || undefined);
    }
    setShowDismissDialog(null);
    setDismissReason('');
  }, [onDismissCandidate, dismissReason]);

  return (
    <div className="candidates-panel">
      {/* Header */}
      <div className="candidates-header">
        <h2>Trade Candidates</h2>
        <div className="candidates-controls">
          <button
            className={`btn-scan ${isScanning ? 'scanning' : ''}`}
            onClick={onScan}
            disabled={isScanning}
          >
            {isScanning ? 'Scanning...' : 'Scan Now'}
          </button>
          <button
            className={`btn-polling ${isPolling ? 'active' : ''}`}
            onClick={onTogglePolling}
          >
            {isPolling ? 'Stop Auto' : 'Start Auto'}
          </button>
        </div>
      </div>

      {/* Stats Summary */}
      <div className="candidates-stats">
        <div className="stat-item">
          <span className="stat-label">Total</span>
          <span className="stat-value">{stats.totalCandidates}</span>
        </div>
        <div className="stat-item">
          <span className="stat-label">New</span>
          <span className="stat-value">{stats.byStatus['new'] ?? 0}</span>
        </div>
        <div className="stat-item">
          <span className="stat-label">Avg Score</span>
          <span className="stat-value">{stats.averageScore.toFixed(0)}</span>
        </div>
        {stats.lastScanAt && (
          <div className="stat-item">
            <span className="stat-label">Last Scan</span>
            <span className="stat-value">{formatTimestamp(stats.lastScanAt)}</span>
          </div>
        )}
      </div>

      {/* Filters */}
      <div className="candidates-filters">
        <div className="filter-group">
          <label>Status:</label>
          <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)}>
            <option value="all">All</option>
            <option value="new">New</option>
            <option value="viewed">Viewed</option>
            <option value="dismissed">Dismissed</option>
            <option value="actioned">Actioned</option>
          </select>
        </div>
        <div className="filter-group">
          <label>Sort by:</label>
          <select value={sortBy} onChange={(e) => setSortBy(e.target.value as 'score' | 'time' | 'symbol')}>
            <option value="score">Score (High to Low)</option>
            <option value="time">Time (Recent First)</option>
            <option value="symbol">Symbol (A-Z)</option>
          </select>
        </div>
      </div>

      {/* Candidates List */}
      <div className="candidates-list">
        {sortedCandidates.length === 0 ? (
          <div className="candidates-empty">
            <p>No candidates found.</p>
            <p className="hint">Run a scan to find trade opportunities.</p>
          </div>
        ) : (
          sortedCandidates.map((candidate) => (
            <div
              key={candidate.id}
              className={`candidate-card ${candidate.status} ${expandedCandidateId === candidate.id ? 'expanded' : ''}`}
            >
              {/* Card Header */}
              <div
                className="candidate-header"
                onClick={() => handleToggleExpand(candidate.id)}
              >
                <div className="candidate-symbol">
                  <span className="symbol">{candidate.symbol}</span>
                  <span className="price">{formatPrice(candidate.currentPrice)}</span>
                </div>
                <div className={`candidate-score ${getScoreColor(candidate.score)}`}>
                  <span className="score-value">{candidate.score}</span>
                  <span className="score-label">Score</span>
                </div>
                <div className="candidate-strategy">
                  <span className="strategy-badge">{formatStrategy(candidate.suggestedStrategy)}</span>
                </div>
                <div className="candidate-status">
                  <span className={`status-badge ${candidate.status}`}>
                    {candidate.status.toUpperCase()}
                  </span>
                </div>
                <div className="candidate-time">
                  {formatTimestamp(candidate.generatedAt)}
                </div>
                <div className="candidate-expand-icon">
                  {expandedCandidateId === candidate.id ? '[-]' : '[+]'}
                </div>
              </div>

              {/* Triggers Summary */}
              <div className="candidate-triggers-summary">
                {candidate.triggers.slice(0, 3).map((trigger, idx) => (
                  <span key={idx} className={`trigger-badge ${getStrengthBadge(trigger.strength)}`}>
                    {formatTriggerType(trigger.type)}
                  </span>
                ))}
                {candidate.triggers.length > 3 && (
                  <span className="trigger-more">+{candidate.triggers.length - 3} more</span>
                )}
              </div>

              {/* Expanded Details */}
              {expandedCandidateId === candidate.id && (
                <div className="candidate-details">
                  {/* Technical Analysis */}
                  <div className="detail-section">
                    <h4>Technical Analysis</h4>
                    <div className="technicals-grid">
                      <div className="tech-item">
                        <span className="tech-label">Trend</span>
                        <span className={`tech-value trend-${candidate.technicals.trend.direction}`}>
                          {getTrendIcon(candidate.technicals.trend.direction)} {candidate.technicals.trend.direction}
                        </span>
                      </div>
                      {candidate.technicals.rsi && (
                        <div className="tech-item">
                          <span className="tech-label">RSI</span>
                          <span className="tech-value">
                            {candidate.technicals.rsi.value.toFixed(1)} ({candidate.technicals.rsi.interpretation})
                          </span>
                        </div>
                      )}
                      {candidate.technicals.atr && (
                        <div className="tech-item">
                          <span className="tech-label">ATR</span>
                          <span className="tech-value">
                            {candidate.technicals.atr.valuePercent.toFixed(2)}% ({candidate.technicals.atr.interpretation})
                          </span>
                        </div>
                      )}
                    </div>
                    {candidate.technicals.trend.signals.length > 0 && (
                      <div className="tech-signals">
                        <span className="signals-label">Signals:</span>
                        {candidate.technicals.trend.signals.map((signal, idx) => (
                          <span key={idx} className="signal-item">{signal}</span>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Triggers */}
                  <div className="detail-section">
                    <h4>Triggers</h4>
                    <div className="triggers-list">
                      {candidate.triggers.map((trigger, idx) => (
                        <div key={idx} className={`trigger-item ${getStrengthBadge(trigger.strength)}`}>
                          <span className="trigger-type">{formatTriggerType(trigger.type)}</span>
                          <span className="trigger-desc">{trigger.description}</span>
                          <span className={`trigger-strength ${trigger.strength}`}>
                            {trigger.strength.toUpperCase()}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Score Breakdown */}
                  <div className="detail-section">
                    <h4>Score Breakdown</h4>
                    <div className="score-breakdown">
                      <div className="score-bar">
                        <span className="score-category">Technical</span>
                        <div className="score-meter">
                          <div
                            className="score-fill technical"
                            style={{ width: `${candidate.scoreBreakdown.technicalScore}%` }}
                          />
                        </div>
                        <span className="score-number">{candidate.scoreBreakdown.technicalScore}</span>
                      </div>
                      <div className="score-bar">
                        <span className="score-category">Research</span>
                        <div className="score-meter">
                          <div
                            className="score-fill research"
                            style={{ width: `${candidate.scoreBreakdown.researchScore}%` }}
                          />
                        </div>
                        <span className="score-number">{candidate.scoreBreakdown.researchScore}</span>
                      </div>
                      <div className="score-bar">
                        <span className="score-category">Liquidity</span>
                        <div className="score-meter">
                          <div
                            className="score-fill liquidity"
                            style={{ width: `${candidate.scoreBreakdown.liquidityScore}%` }}
                          />
                        </div>
                        <span className="score-number">{candidate.scoreBreakdown.liquidityScore}</span>
                      </div>
                    </div>
                  </div>

                  {/* Research Context */}
                  {candidate.researchContext.length > 0 && (
                    <div className="detail-section">
                      <h4>Related Research</h4>
                      <div className="research-list">
                        {candidate.researchContext.slice(0, 3).map((ref) => (
                          <div key={ref.id} className="research-item">
                            <span className={`research-sentiment ${getSentimentBadge(ref.sentiment)}`}>
                              {ref.sentiment ?? 'N/A'}
                            </span>
                            <span className="research-headline">{ref.headline}</span>
                            <span className="research-source">{ref.sourceName}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Strategy Rationale */}
                  <div className="detail-section">
                    <h4>Strategy Rationale</h4>
                    <p className="rationale-text">{candidate.strategyRationale}</p>
                  </div>

                  {/* Warnings */}
                  {candidate.warnings.length > 0 && (
                    <div className="detail-section warnings-section">
                      <h4>!! Warnings</h4>
                      <ul className="warnings-list">
                        {candidate.warnings.map((warning, idx) => (
                          <li key={idx} className="warning-item">{warning}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Actions */}
                  <div className="candidate-actions">
                    {candidate.proposalId ? (
                      <button
                        className="btn-primary"
                        onClick={() => onApproveCandidate?.(candidate.id)}
                      >
                        Review Proposal
                      </button>
                    ) : (
                      <button
                        className="btn-primary"
                        onClick={() => onCreateProposal?.(candidate.id)}
                      >
                        Create Proposal
                      </button>
                    )}
                    <button
                      className="btn-secondary"
                      onClick={() => setShowDismissDialog(candidate.id)}
                    >
                      Dismiss
                    </button>
                  </div>
                </div>
              )}
            </div>
          ))
        )}
      </div>

      {/* Dismiss Dialog */}
      {showDismissDialog && (
        <div className="modal-overlay">
          <div className="dismiss-dialog">
            <h3>Dismiss Candidate</h3>
            <p>Are you sure you want to dismiss this candidate?</p>
            <div className="dismiss-reason">
              <label>Reason (optional):</label>
              <input
                type="text"
                value={dismissReason}
                onChange={(e) => setDismissReason(e.target.value)}
                placeholder="e.g., Already have position, Not interested"
              />
            </div>
            <div className="dialog-actions">
              <button
                className="btn-secondary"
                onClick={() => {
                  setShowDismissDialog(null);
                  setDismissReason('');
                }}
              >
                Cancel
              </button>
              <button
                className="btn-primary"
                onClick={() => handleDismiss(showDismissDialog)}
              >
                Dismiss
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CandidatesPanel;
